### ISSUE TITLE
For Detialed Code

### ISSUE THREAD

**Issue by dragonlee258079** [Sissuire/RR-IQA-AVCD#1]
Hi, I am Long LI, a Ph.D. student at Northwestern Polytechnical University. We are searching for a task in which we can apply our rank saliency work. I read your paper entitled  "Saliency change based reduced reference image quality assessment" and am very interested in this work. We want to follow your nice work and apply our rank saliency result in it. However, we can't access the detailed code.  I am wondering that could you share the detialed code with me. I will appreciate your help and cite your nice work. My email is longli.nwpu@gmail.com.

Thanks for considering my request!

**Comment by Sissuire** [comment]
@dragonlee258079 Thanks for your interest. The code will be sent by the email.

**Comment by dragonlee258079** [comment]
Thanks a lot.

**Comment by dragonlee258079** [comment]
@Sissuire  Sorry to bother you again. Has the code been posted yet? I did not receive it in my mailbox.
